spring:
  datasource:
    url: &dbURL jdbc:mysql://localhost:3306/crud_db
    username: &dbUser root
    password: &dbPassword pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update